# Generated by Django 3.2.6 on 2022-11-26 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requirement',
            options={'verbose_name_plural': 'Requirements'},
        ),
    ]
