# Generated by Django 3.2.6 on 2021-10-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Required and Unique', max_length=255, unique=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(default=None, max_length=1000),
        ),
    ]
