# Generated by Django 3.2.6 on 2022-07-17 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='staff',
            field=models.CharField(blank=True, default='admin', max_length=100, null=True),
        ),
    ]
