# Generated by Django 3.2.6 on 2022-08-15 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebook',
            name='file',
        ),
        migrations.RemoveField(
            model_name='facebook',
            name='link',
        ),
        migrations.RemoveField(
            model_name='twitter',
            name='link',
        ),
    ]
