# Generated by Django 4.0.3 on 2022-03-21 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='task',
            name='slug',
        ),
        migrations.AddField(
            model_name='task',
            name='duration',
            field=models.PositiveIntegerField(default=1, error_messages={'name': {' max_length': 'Points must be less than Maximum Points'}}, help_text='Should be less than Maximum Points assigned'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(choices=[('Meetings', 'Meetings'), ('Data Analysis', 'Data Analysis'), ('Stocks & Options', 'Stocks & Options'), ('Website Development', 'Website Development'), ('Department', 'Department'), ('Other', 'Other')], default='Other', max_length=55, unique=True),
        ),
    ]
