# Generated by Django 3.2.6 on 2022-08-09 19:11

from django.db import migrations, models
import django.db.models.deletion
import management.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Group A', help_text='Required', max_length=255, verbose_name='group')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='group',
            field=models.ForeignKey(default=management.models.TaskGroups.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='management.taskgroups'),
        ),
    ]
