# Generated by Django 3.2.6 on 2022-09-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payslipconfig',
            name='eom_bonus_percentage',
            field=models.DecimalField(decimal_places=2, default=0.02, max_digits=5),
        ),
        migrations.AddField(
            model_name='payslipconfig',
            name='eoq_bonus_percentage',
            field=models.DecimalField(decimal_places=2, default=0.02, max_digits=5),
        ),
        migrations.AddField(
            model_name='payslipconfig',
            name='eoy_bonus_percentage',
            field=models.DecimalField(decimal_places=2, default=0.02, max_digits=5),
        ),
        migrations.AlterField(
            model_name='laptopbonus',
            name='period',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='laptopsaving',
            name='period',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='loan',
            name='period',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='monthlypoints',
            name='period',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='period',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='payslipconfig',
            name='rp_starting_period',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='quarterlypoints',
            name='period',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='retirementpackage',
            name='period',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='yearlypoints',
            name='period',
            field=models.CharField(max_length=10),
        ),
    ]
