# Generated by Django 3.2.6 on 2023-09-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GotoMeetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_topic', models.CharField(blank=True, max_length=250, null=True)),
                ('meeting_id', models.CharField(blank=True, max_length=100, null=True)),
                ('meeting_type', models.CharField(blank=True, max_length=100, null=True)),
                ('recording', models.CharField(blank=True, max_length=500, null=True)),
                ('meeting_start_time', models.CharField(blank=True, max_length=250, null=True)),
                ('meeting_end_time', models.CharField(blank=True, max_length=250, null=True)),
                ('meeting_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('meeting_email', models.CharField(blank=True, max_length=150, null=True)),
                ('attendee_name', models.CharField(blank=True, max_length=150, null=True)),
                ('attendee_email', models.CharField(blank=True, max_length=150, null=True)),
                ('attendee_duration', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=True)),
            ],
        ),
    ]
