# Generated by Django 3.2.6 on 2021-10-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='point',
            field=models.PositiveIntegerField(error_messages={'name': {' max_length': 'Points must be less than Maximum Points'}}, help_text='Should be less than Maximum Points assigned'),
        ),
    ]
