# Generated by Django 3.2.6 on 2022-09-13 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
    ]
