# Generated by Django 3.2.6 on 2022-09-15 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20220912_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslipconfig',
            name='eom_bonus_percentage',
        ),
        migrations.RemoveField(
            model_name='payslipconfig',
            name='eoq_bonus_percentage',
        ),
        migrations.RemoveField(
            model_name='payslipconfig',
            name='eoy_bonus_percentage',
        ),
    ]
