# Generated by Django 3.2.6 on 2022-08-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20220809_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskgroups',
            name='title',
            field=models.CharField(default='Group A', max_length=55, unique=True),
        ),
    ]
