# Generated by Django 3.2.6 on 2022-09-18 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20220913_0822'),
        ('management', '0003_auto_20220915_0657'),
    ]

    operations = [
    ]
