# Generated by Django 4.0.3 on 2022-03-21 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_remove_task_category_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='slug',
            field=models.SlugField(blank=True, default='slug', max_length=255),
        ),
    ]
