# Generated by Django 3.2.6 on 2022-03-02 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0003_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-submission',), 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(default=999, on_delete=django.db.models.deletion.RESTRICT, related_name='user_assiged', to=settings.AUTH_USER_MODEL),
        ),
    ]
