# Generated by Django 3.2.6 on 2022-02-20 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20220220_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='department',
            field=models.CharField(choices=[('HR', 'HR'), ('IT', 'IT'), ('Marketing', 'Marketing'), ('Finance', 'Finance'), ('Security', 'Security'), ('Management', 'Management'), ('Health', 'Health'), ('Other', 'Other')], default='Other', max_length=100),
        ),
    ]
