# Generated by Django 4.0.3 on 2022-03-21 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_task_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='employee',
        ),
    ]
