# Generated by Django 3.2.6 on 2022-05-29 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0006_taskhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Reporting', 'Reporting'), ('ETL', 'ETL'), ('Database', 'Database'), ('Website', 'Website'), ('Other', 'Other')], default='Other', max_length=25)),
                ('requestor', models.CharField(choices=[('Management', 'Management'), ('Client', 'Client'), ('Other', 'Other')], default='Other', max_length=25)),
                ('created_by', models.CharField(default='admin', max_length=255)),
                ('app', models.CharField(default='Data Analysis', max_length=255)),
                ('duration', models.IntegerField(default=4)),
                ('delivery_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('what', models.TextField()),
                ('why', models.TextField()),
                ('how', models.TextField()),
                ('doc', models.FileField(blank=True, null=True, upload_to='Uploads/Support_Docs/')),
                ('assigned_to', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Requirements',
            },
        ),
    ]
