# Generated by Django 3.2.6 on 2022-06-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_requirement_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
