# Generated by Django 3.2.6 on 2022-06-21 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0011_facebook_twitter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='assigned_to',
            field=models.ForeignKey(default=1, limit_choices_to={'is_employee': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
