# Generated by Django 3.2.6 on 2022-07-03 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0013_alter_task_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(default='General', max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc', models.FileField(default='None', upload_to='evidence/docs/')),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('linkpassword', models.CharField(default='No Password Needed', max_length=255)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Is featured')),
                ('added_by', models.ForeignKey(limit_choices_to=models.Q(('is_employee', True), ('is_admin', True), ('is_superuser', True), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ManyToManyField(blank=True, related_name='task_featured', to='management.Task')),
            ],
            options={
                'verbose_name_plural': 'links',
            },
        ),
    ]
