# Generated by Django 3.2.6 on 2022-07-01 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_alter_requirement_assigned_to'),
        ('management', '0013_alter_task_employee'),
    ]

    operations = [
    ]
