# Generated by Django 3.2.6 on 2022-07-03 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_merge_20220701_1207'),
        ('management', '0014_merge_20220701_1228'),
    ]

    operations = [
    ]
