# Generated by Django 3.2.6 on 2022-07-06 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_merge_20220703_0859'),
        ('management', '0020_merge_20220703_2308'),
    ]

    operations = [
    ]
