# Generated by Django 3.2.6 on 2022-07-08 02:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0020_auto_20220707_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklinks',
            name='added_by',
            field=models.ForeignKey(default=1, limit_choices_to=models.Q(('is_employee', True), ('is_admin', True), ('is_superuser', True), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tasklinks',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tasklinks',
            name='link_name',
            field=models.CharField(default='General', max_length=255),
        ),
    ]
