# Generated by Django 3.2.6 on 2022-07-08 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_auto_20220707_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklinks',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
