# Generated by Django 3.2.6 on 2022-08-29 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_auto_20220709_1120'),
        ('management', '0024_auto_20220709_1326'),
    ]

    operations = [
    ]
