# Generated by Django 4.0.4 on 2022-07-17 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_auto_20220709_1120'),
        ('management', '0024_auto_20220709_1326'),
    ]

    operations = [
    ]
