# Generated by Django 3.2.6 on 2022-08-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0025_merge_0021_auto_20220709_1120_0024_auto_20220709_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhistory',
            name='mxpoint',
            field=models.DecimalField(decimal_places=2, error_messages={'name': {' max_length': 'The maximum points must be between 0 and 199'}}, help_text='Maximum 200', max_digits=10),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='point',
            field=models.DecimalField(decimal_places=2, error_messages={'name': {' max_length': 'Points must be less than Maximum Points'}}, help_text='Should be less than Maximum Points assigned', max_digits=10),
        ),
    ]
