# Generated by Django 3.2.6 on 2022-07-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0026_auto_20220717_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policy',
            name='is_internal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
