# Generated by Django 3.2.6 on 2022-07-17 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0027_auto_20220717_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='last_name',
        ),
        migrations.AddField(
            model_name='policy',
            name='staff',
            field=models.ForeignKey(default=999, limit_choices_to=models.Q(('is_employee', True), ('is_admin', True), ('is_superuser', True), _connector='OR'), on_delete=django.db.models.deletion.RESTRICT, related_name='staff_entry', to=settings.AUTH_USER_MODEL),
        ),
    ]
