# Generated by Django 3.2.6 on 2023-09-29 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients_category', models.CharField(choices=[('DYC', 'Diaspora Youth Caucus'), ('DC48KENYA', 'DC48KENYA'), ('Other', 'Other')], default='Other', max_length=25)),
                ('category', models.CharField(choices=[('Conference Facilities', 'Conference Facilities'), ('Food', 'Food'), ('Entertainment', 'Entertainment'), ('Travel', 'Travel'), ('Accomodation', 'Accomodation'), ('Awards', 'Awards'), ('Media Coverage', 'Media Coverage'), ('Other', 'Other')], default='Other', max_length=25)),
                ('item', models.CharField(default=None, max_length=100, null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('qty', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('description', models.TextField(default=None, max_length=1000)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('receipt_link', models.CharField(blank=True, max_length=100, null=True)),
                ('budget_lead', models.ForeignKey(limit_choices_to=models.Q(('sub_category', 6), ('sub_category', 7), ('is_superuser', True), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='budget_lead', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='laptop_saving',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='loan',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='retirement_package',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='user',
        ),
        migrations.RemoveField(
            model_name='retirementpackage',
            name='user',
        ),
        migrations.DeleteModel(
            name='LaptopSaving',
        ),
        migrations.DeleteModel(
            name='Payslip',
        ),
        migrations.DeleteModel(
            name='RetirementPackage',
        ),
    ]
