# Generated by Django 3.2.6 on 2022-11-06 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('phone', models.CharField(default='90001', help_text='Start with Country Code ie 254******', max_length=100)),
                ('location', models.CharField(default='Makutano', max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('featured', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('added_by', models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'is_employee': True}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='staff', to=settings.AUTH_USER_MODEL, verbose_name='staff')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255, unique=True)),
                ('unit_amt', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('qty', models.PositiveIntegerField()),
                ('bal_qty', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('supplier', models.ForeignKey(limit_choices_to=models.Q(('active', True)), on_delete=django.db.models.deletion.RESTRICT, to='finance.supplier')),
            ],
        ),
    ]
