# Generated by Django 3.2.6 on 2022-09-06 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='default_payment_fees',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='trainingloan',
            name='balance_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='trainingloan',
            name='detection_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='trainingloan',
            name='detection_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingloan',
            name='total_earnings_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='trainingloan',
            name='training_loan_amount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.default_payment_fees'),
        ),
        migrations.CreateModel(
            name='LoanUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_loan', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
