# Generated by Django 3.2.6 on 2022-09-06 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetirementPackageConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_amount', models.DecimalField(decimal_places=2, default=10000, max_digits=10)),
                ('increment_percentage', models.DecimalField(decimal_places=2, default=0.5, max_digits=5)),
                ('increment_max_percentage', models.DecimalField(decimal_places=2, default=5, max_digits=5)),
                ('increment_percentage_increment', models.DecimalField(decimal_places=2, default=0.5, max_digits=5)),
                ('increment_percentage_increment_cycle', models.IntegerField(default=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RetirementPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('points', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('EOM', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('EOQ', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('EOY', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('laptop_bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('holiday_wages', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('night_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('retirement_package', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('training_loan', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('FA', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('computer_maintenance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('health_care', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('laptop_service', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
