# Generated by Django 3.2.6 on 2024-02-10 14:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0002_auto_20240210_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheetentry',
            name='balance_sheet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='finance.balancesheetsummary'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='balancesheetentry',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='finance.balancesheetcategory'),
            preserve_default=False,
        ),

    ]
