# Generated by Django 3.2.6 on 2022-11-26 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_food_supplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-activity_date'], 'verbose_name_plural': 'Transactions'},
        ),
    ]
