# Generated by Django 3.2.6 on 2024-01-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20230929_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_history',
            name='subplan',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payment_information',
            name='subplan',
            field=models.IntegerField(null=True),
        ),
    ]
