# Generated by Django 3.2.6 on 2023-08-23 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_transaction_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='default_payment_fees',
            name='loan_amount',
        ),
    ]
