# Generated by Django 3.2.6 on 2024-02-13 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0003_auto_20240210_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancesheetentry',
            name='amount',
        ),
        migrations.AddField(
            model_name='balancesheetcategory',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
