# Generated by Django 3.2.6 on 2022-09-07 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_payslipconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslipconfig',
            name='user',
        ),
        migrations.RemoveField(
            model_name='retirementpackage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='retirementpackageconfig',
            name='user',
        ),
        migrations.DeleteModel(
            name='Payslip',
        ),
        migrations.DeleteModel(
            name='PayslipConfig',
        ),
        migrations.DeleteModel(
            name='RetirementPackage',
        ),
        migrations.DeleteModel(
            name='RetirementPackageConfig',
        ),
    ]
