# Generated by Django 3.2.6 on 2024-03-15 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_coda_assets'),
        ('finance', '0002_company_assets'),
        ('finance', '0003_auto_20240116_1040'),
        ('finance', '0004_auto_20240213_1956'),
    ]

    operations = [
    ]
