# Generated by Django 3.2.6 on 2021-09-04 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codablog', '0002_rated'),
    ]

    operations = [
        migrations.AddField(
            model_name='rated',
            name='rater',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
