# Generated by Django 3.2.6 on 2021-09-05 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codablog', '0004_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='rater',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='topic',
            new_name='title',
        ),
    ]
