# Generated by Django 3.2.6 on 2021-09-18 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codablog', '0005_auto_20210904_2208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rated',
            options={'verbose_name_plural': 'Ratings'},
        ),
    ]
