# Generated by Django 3.0.7 on 2021-06-08 01:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('upload_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('doc_type', models.CharField(choices=[('PM', 'Project_Management'), ('BA', 'Business_Analysis'), ('QA', 'Quality_Assurance'), ('UI', 'User_Experience'), ('REP', 'Reporting'), ('ETL', 'ETL'), ('DBA', 'Database'), ('PY', 'Python'), ('OT', 'Other')], default='OT', max_length=10)),
                ('resume', models.FileField(upload_to='cvs/doc/')),
                ('introduction', models.FileField(blank=True, null=True, upload_to='intro/doc/')),
                ('project_Story', models.FileField(blank=True, null=True, upload_to='pm/doc/')),
                ('sdlc', models.FileField(blank=True, null=True, upload_to='sdlc/doc/')),
                ('environment', models.FileField(default='None', upload_to='environment/doc/')),
                ('performance', models.FileField(default='None', upload_to='performance/doc/')),
                ('testing', models.FileField(default='None', upload_to='testing/doc/')),
            ],
        ),
    ]
