# Generated by Django 3.2.6 on 2021-10-20 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='document_date',
        ),
    ]
