# Generated by Django 3.0.7 on 2021-06-08 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='doc_type',
            field=models.CharField(choices=[('Project Management', 'Project_Management'), ('Business Analyst', 'Business_Analysis'), ('Quality Assurance', 'Quality_Assurance'), ('User Interface', 'User_Experience'), ('Reporting', 'Reporting'), ('ETL', 'ETL'), ('Database', 'Database'), ('Python', 'Python'), ('Other', 'Other')], default='Other', max_length=30),
        ),
    ]
