# Generated by Django 3.2.6 on 2022-03-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewupload',
            name='user',
        ),
        migrations.AddField(
            model_name='interviewupload',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='interviewupload',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
