# Generated by Django 3.2.6 on 2024-01-18 11:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylinks',
            name='Featuredsubcategory',
            field=models.ManyToManyField(blank=True, related_name='subcategorie_fetured', to='data.FeaturedSubCategory'),
        ),
    ]