# Generated by Django 3.2.6 on 2022-03-06 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Upload',
            new_name='DocUpload',
        ),
    ]
