# Generated by Django 3.2.6 on 2021-09-21 23:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='first_name',
            new_name='doc_name',
        ),
        migrations.RenameField(
            model_name='upload',
            old_name='last_name',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='environment',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='performance',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='project_Story',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='sdlc',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='testing',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='upload_date',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='username',
        ),
        migrations.AddField(
            model_name='upload',
            name='doc',
            field=models.FileField(default=None, upload_to='Uploads/doc/'),
        ),
        migrations.AddField(
            model_name='upload',
            name='document_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='upload',
            name='doc_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
