# Generated by Django 3.2.6 on 2022-02-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewupload',
            name='featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='interviewupload',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
