# Generated by Django 3.2.6 on 2023-11-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviews',
            name='dynamic_fields',
            field=models.TextField(blank=True, null=True),
        ),
    ]
