# Generated by Django 3.2.6 on 2021-09-22 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20210921_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='doc',
            field=models.FileField(upload_to='Uploads/doc/'),
        ),
    ]
