# Generated by Django 3.2.6 on 2024-01-24 07:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20240124_1232'),
    ]

    operations = [
       
        migrations.RemoveField(
            model_name='activitylinks',
            name='Featuredsubcategory',
        ),
        migrations.AddField(
            model_name='activitylinks',
            name='Featuredsubcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategorie_fetured', to='data.featuredsubcategory'),
        ),
        migrations.AlterField(
            model_name='featuredcategory',
            name='title',
            field=models.CharField(choices=[('Course Overview', 'Course Overview'), ('Initiation & Planning', 'Initiation & Planning'), ('Development', 'Development'), ('Testing', 'Testing'), ('VIDEOS', 'VIDEOS'), ('POWER POINTS', 'POWER POINTS'), ('Deployment', 'Deployment'), ('Other', 'Other')], default='Other', max_length=25, unique=True),
        ),
    ]
