# Generated by Django 3.2.6 on 2023-08-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_prep_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviews',
            name='doc',
            field=models.FileField(default='None', null=True, upload_to='Uploads/doc/'),
        ),
    ]
