# Generated by Django 4.0.3 on 2022-03-27 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_rename_client_interview_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredcategory',
            name='is_active',
        ),
    ]
