# Generated by Django 4.0.3 on 2022-03-13 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_interviewupload_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewupload',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
