# Generated by Django 3.2.6 on 2022-02-23 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0002_auto_20220223_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewupload',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='interviewupload',
            name='last_name',
        ),
        migrations.AddField(
            model_name='interviewupload',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
