# Generated by Django 3.0.7 on 2021-06-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20210607_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='doc_type',
            field=models.CharField(choices=[('Project Management', 'Project Management'), ('Business Analyst', 'Business Analysis'), ('Quality Assurance', 'Quality Assurance'), ('User Interface', 'User Experience'), ('Reporting', 'Reporting'), ('ETL', 'ETL'), ('Database', 'Database'), ('Python', 'Python'), ('Other', 'Other')], default='Other', max_length=25),
        ),
    ]
