# Generated by Django 3.2.6 on 2022-09-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_rename_activity_name_featuredactivity_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredactivity',
            name='slug',
            field=models.SlugField(blank=True, default='slug', max_length=255),
        ),
    ]
