# Generated by Django 4.0.3 on 2022-04-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_dsu'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsu',
            name='uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dsu',
            name='category',
            field=models.CharField(choices=[('Interview', 'Interview'), ('BI Training', 'BI Training'), ('Other', 'Other')], default='Other', max_length=25, unique=True),
        ),
    ]
