# Generated by Django 3.2.6 on 2023-02-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_featuredsubcategory_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingresponsestracking',
            name='course_overview',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
