# Generated by Django 4.0.3 on 2022-03-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_alter_featuredcategory_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredcategory',
            name='title',
            field=models.CharField(choices=[('Course Overview', 'Course Overview'), ('Initiation & Planning', 'Initiation & Planning'), ('Development', 'Development'), ('Testing', 'Testing'), ('Deployment', 'Deployment'), ('Other', 'Other')], default='Other', max_length=25, unique=True),
        ),
    ]
