# Generated by Django 3.2.6 on 2022-02-23 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20220223_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewupload',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='interviewupload',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
