# Generated by Django 4.0.3 on 2022-03-27 23:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_remove_featuredcategory_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredcategory',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
