# Generated by Django 4.0.3 on 2022-03-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_featuredcategory_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlevel',
            name='level',
            field=models.CharField(choices=[('Level A', 'Level A'), ('Level B', 'Level B'), ('Level C', 'Level C'), ('Level D', 'Level D'), ('Level E', 'Level E'), ('Other', 'Other')], default='Level A', max_length=25, unique=True),
        ),
    ]
