# Generated by Django 4.0.3 on 2022-04-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_dsu_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dsu',
            name='type',
            field=models.CharField(choices=[('client', 'client'), ('Staff', 'Staff'), ('Other', 'Other')], default='Other', max_length=25),
        ),
        migrations.AlterField(
            model_name='dsu',
            name='category',
            field=models.CharField(choices=[('Interview', 'Interview'), ('BI Training', 'BI Training'), ('Other', 'Other')], default='Other', max_length=25),
        ),
    ]
