# Generated by Django 4.0.3 on 2022-03-23 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0005_alter_userlevel_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='user',
        ),
        migrations.AddField(
            model_name='interview',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='client_assiged', to=settings.AUTH_USER_MODEL),
        ),
    ]
