# Generated by Django 3.2.6 on 2023-08-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_interviews_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviews',
            name='doc',
            field=models.FileField(blank=True, default='None', upload_to='Uploads/doc/'),
        ),
    ]
