# Generated by Django 4.0.3 on 2022-03-27 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_featuredcategory_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featuredcategory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='featuredcategory',
            name='created_by',
        ),
    ]
