# Generated by Django 3.2.6 on 2021-09-18 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20210820_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewupload',
            options={'verbose_name_plural': 'InterviewUpload'},
        ),
        migrations.AlterModelOptions(
            name='upload',
            options={'verbose_name_plural': 'Upload'},
        ),
    ]
