# Generated by Django 4.0.3 on 2022-04-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_remove_dsu_is_active_dsu_cohort'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dsu',
            name='category',
            field=models.CharField(choices=[('Interview', 'Interview'), ('BI Training', 'BI Training'), ('Job Support', 'Job Support'), ('Other', 'Other')], default='Other', max_length=25),
        ),
    ]
