# Generated by Django 3.2.6 on 2023-08-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_interviews_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviews',
            name='dynamic_fields',
            field=models.TextField(blank=True, null=True),
        ),
    ]
