# Generated by Django 4.0.3 on 2022-04-28 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0007_alter_dsu_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('recruiter', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_phone', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_tool', models.CharField(blank=True, max_length=100, null=True)),
                ('secondary_tool', models.CharField(blank=True, max_length=100, null=True)),
                ('job_location', models.CharField(blank=True, max_length=100, null=True)),
                ('offer', models.DecimalField(decimal_places=2, error_messages={'name': {' max_length': 'The earning must be between 0 and 4999.99'}}, max_digits=10)),
                ('status', models.CharField(choices=[('screening call', 'screening call'), ('1st interview', '1st interview'), ('2nd interview', '2nd interview'), ('3rd interview', '3rd interview'), ('Other', 'Other')], default='other', max_length=25)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_resume', models.FileField(default='None', upload_to='training/docs/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'jobs',
            },
        ),
    ]
