# Generated by Django 3.2.6 on 2023-12-22 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whatsapp_Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=100, null=True)),
                ('group_id', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('investments', 'investments'), ('data_analysis', 'data_analysis'), ('coda', 'coda'), ('Job_Support', 'Job_Support'), ('interview', 'interview'), ('mentorship', 'mentorship'), ('other', 'other')], default='other', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_title', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('short_name', models.CharField(blank=True, max_length=50, null=True)),
                ('company_site', models.CharField(blank=True, max_length=255, null=True)),
                ('meeting_link', models.CharField(blank=True, max_length=500, null=True)),
                ('video_link', models.CharField(blank=True, max_length=500, null=True)),
                ('signature', models.CharField(blank=True, max_length=255, null=True)),
                ('bulletin', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('image_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='message_image', to='main.assets')),
            ],
        ),
    ]
