# Generated by Django 3.2.6 on 2024-01-16 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whatsapp_dev',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_id', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('group_name', models.CharField(blank=True, max_length=100, null=True)),
                ('participants', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(choices=[('Finance', 'Finance'), ('IT', 'IT'), ('Internal', 'Internal'), ('Political', 'Political'), ('Business', 'Business'), ('other', 'other')], default='other', max_length=25)),
                ('type', models.CharField(choices=[('investments', 'investments'), ('data_analysis', 'data_analysis'), ('coda', 'coda'), ('Job_Support', 'Job_Support'), ('interview', 'interview'), ('mentorship', 'mentorship'), ('other', 'other')], default='other', max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ads',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ads',
            name='my_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='whatsapp_groups',
            name='category',
            field=models.CharField(choices=[('Finance', 'Finance'), ('IT', 'IT'), ('Internal', 'Internal'), ('Political', 'Political'), ('Business', 'Business'), ('other', 'other')], default='other', max_length=25),
        ),
        migrations.AddField(
            model_name='whatsapp_groups',
            name='participants',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='whatsapp_groups',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ads',
            name='bulletin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='whatsapp_groups',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='whatsapp_groups',
            name='type',
            field=models.CharField(choices=[('investments', 'investments'), ('data_analysis', 'data_analysis'), ('coda', 'coda'), ('Job_Support', 'Job_Support'), ('interview', 'interview'), ('mentorship', 'mentorship'), ('automation', 'automation'), ('other', 'other')], default='other', max_length=25),
        ),
    ]
