# Generated by Django 3.2.6 on 2022-10-27 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_in_code', models.CharField(blank=True, max_length=255, null=True)),
                ('reason_code_crash', models.CharField(blank=True, max_length=255, null=True)),
                ('exception', models.CharField(blank=True, max_length=255, null=True)),
                ('api', models.URLField(blank=True, max_length=255, null=True)),
                ('crated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_in_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
