# Generated by Django 3.2.6 on 2021-10-07 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='updated',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
