# Generated by Django 3.2.6 on 2021-10-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_test_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='updated',
            field=models.DateField(default='12/31/9999'),
        ),
    ]
