# Generated by Django 3.2.6 on 2021-10-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_alter_test_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='updated',
        ),
        migrations.AddField(
            model_name='test',
            name='mxpoint',
            field=models.CharField(default=10, max_length=200),
        ),
    ]
