# Generated by Django 3.2.6 on 2021-10-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_auto_20211007_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='point',
            field=models.PositiveBigIntegerField(default=10),
        ),
    ]
