# Generated by Django 3.2.6 on 2021-10-07 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0007_test_point'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='mxpoint',
            new_name='earning',
        ),
    ]
