# Generated by Django 3.2.6 on 2021-10-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0008_rename_mxpoint_test_earning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='result',
        ),
        migrations.AddField(
            model_name='test',
            name='mxpoint',
            field=models.PositiveBigIntegerField(default=10),
        ),
    ]
