# Generated by Django 3.2.6 on 2021-10-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0009_auto_20211007_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='updated',
            field=models.CharField(default='10/07/2021', max_length=200),
        ),
    ]
