# Generated by Django 3.2.6 on 2021-10-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0011_alter_test_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created on'),
        ),
    ]
