# Generated by Django 3.2.6 on 2021-10-07 10:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0012_alter_test_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
