# Generated by Django 3.2.6 on 2021-10-07 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0013_alter_test_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='updated',
        ),
    ]
