# Generated by Django 3.2.6 on 2021-10-07 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0014_remove_test_updated'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Activity',
        ),
    ]
