# Generated by Django 3.2.6 on 2021-10-10 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0015_rename_test_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='updated',
        ),
    ]
