# Generated by Django 3.2.6 on 2023-04-06 07:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='covered_calls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symbol', models.CharField(max_length=255)),
                ('Action', models.CharField(max_length=255)),
                ('Expiry', models.CharField(max_length=255)),
                ('Days_To_Expiry', models.CharField(max_length=255)),
                ('Strike_Price', models.CharField(max_length=255)),
                ('Mid_Price', models.CharField(max_length=255)),
                ('Bid_Price', models.CharField(max_length=255)),
                ('Ask_Price', models.CharField(max_length=255)),
                ('Implied_Volatility_Rank', models.CharField(max_length=255)),
                ('Earnings_Date', models.CharField(max_length=255)),
                ('Stock_Price', models.CharField(max_length=255)),
                ('Raw_Return', models.CharField(max_length=255)),
                ('Annualized_Return', models.CharField(max_length=255)),
                ('Distance_To_Strike', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'covered_calls',
            },
        ),
        migrations.CreateModel(
            name='cread_spread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symbol', models.CharField(max_length=255)),
                ('Strategy', models.CharField(max_length=255)),
                ('Type', models.CharField(max_length=255)),
                ('Price', models.CharField(max_length=255)),
                ('Sell_Strike', models.CharField(max_length=255)),
                ('Buy_Strike', models.CharField(max_length=255)),
                ('Expiry', models.CharField(max_length=255)),
                ('Premium', models.CharField(max_length=255)),
                ('Width', models.CharField(max_length=255)),
                ('Prem_Width', models.CharField(max_length=255)),
                ('Rank', models.CharField(max_length=255)),
                ('Earnings_Date', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'cread_spread',
            },
        ),
        migrations.CreateModel(
            name='cryptomarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'cryptomarket',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('doc_type', models.CharField(blank=True, max_length=100, null=True)),
                ('doc_name', models.CharField(blank=True, max_length=100, null=True)),
                ('doc', models.FileField(upload_to='document/doc/')),
            ],
            options={
                'verbose_name_plural': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='ShortPut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symbol', models.CharField(max_length=255)),
                ('Action', models.CharField(max_length=255)),
                ('Expiry', models.CharField(max_length=255)),
                ('Days_To_Expiry', models.CharField(max_length=255)),
                ('Strike_Price', models.CharField(max_length=255)),
                ('Mid_Price', models.CharField(max_length=255)),
                ('Bid_Price', models.CharField(max_length=255)),
                ('Ask_Price', models.CharField(max_length=255)),
                ('Implied_Volatility_Rank', models.CharField(max_length=255)),
                ('Earnings_Date', models.CharField(max_length=255)),
                ('Stock_Price', models.CharField(max_length=255)),
                ('Raw_Return', models.CharField(max_length=255)),
                ('Annualized_Return', models.CharField(max_length=255)),
                ('Distance_To_Strike', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'ShortPut',
            },
        ),
        migrations.CreateModel(
            name='stockmarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('qty', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'stockmarket',
            },
        ),
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('doc_type', models.CharField(blank=True, max_length=100, null=True)),
                ('doc_name', models.CharField(blank=True, max_length=100, null=True)),
                ('doc', models.FileField(upload_to='Uploads/doc/')),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Uploads',
            },
        ),
    ]
