# Generated by Django 3.2.6 on 2024-02-02 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='overboughtsold',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='overboughtsold',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
