# Generated by Django 3.2.6 on 2023-08-31 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oversold',
            name='on_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
