# Generated by Django 3.2.6 on 2024-01-16 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portifolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('symbol', models.CharField(blank=True, max_length=255, null=True)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('action', models.CharField(blank=True, max_length=255, null=True)),
                ('implied_volatility_rank', models.CharField(blank=True, max_length=255, null=True)),
                ('expiry', models.CharField(blank=True, max_length=255, null=True)),
                ('earnings_date', models.CharField(blank=True, max_length=255, null=True)),
                ('condition', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('on_date', models.CharField(blank=True, max_length=255, null=True)),
                ('strategy', models.CharField(blank=True, max_length=255, null=True)),
                ('returns', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('short_strike', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('long_strike', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('long_leg_delta', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('short_leg_delta', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('long_leg_theta', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('short_leg_theta', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('number_of_contract', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'portifolio',
            },
        ),
        migrations.DeleteModel(
            name='Oversold',
        ),
        migrations.RenameField(
            model_name='credit_spread',
            old_name='comment',
            new_name='rank',
        ),
        migrations.RemoveField(
            model_name='credit_spread',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='credit_spread',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='credit_spread',
            name='iv_rank',
        ),
        migrations.RemoveField(
            model_name='credit_spread',
            name='on_date',
        ),
        migrations.AddField(
            model_name='investor_information',
            name='investment_threshold',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='ticker_data',
            name='industry',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
