# Generated by Django 3.0.7 on 2021-02-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0002_uploads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
