# Generated by Django 3.2.6 on 2023-08-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0002_oversold_on_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='covered_calls',
            name='on_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='credit_spread',
            name='on_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shortput',
            name='on_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
