# Generated by Django 3.2.6 on 2021-09-22 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investing', '0005_employees'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employees',
        ),
    ]
