# Generated by Django 3.0.7 on 2021-05-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], default=9999),
        ),
    ]
