# Generated by Django 3.2.6 on 2022-03-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='Plan',
            field=models.CharField(default='Plan B', help_text='Required', max_length=255, verbose_name='group'),
        ),
        migrations.AddField(
            model_name='tracker',
            name='time',
            field=models.PositiveIntegerField(default=120, error_messages={'name': {' max_length': 'The maximum hours must be between 0 and 199'}}, help_text='Maximum 200'),
        ),
    ]
