# Generated by Django 3.2.6 on 2023-02-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='is_employee_contract_signed',
            field=models.BooleanField(default=False),
        ),
    ]
