# Generated by Django 3.2.6 on 2022-06-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeruser',
            options={'ordering': ['-date_joined']},
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='sub_category',
            field=models.IntegerField(blank=True, choices=[(0, 'No Selection'), (1, 'Job Support'), (2, 'Student'), (3, 'Full Time'), (4, 'Contractual'), (5, 'Agent'), (6, 'Other')], null=True),
        ),
    ]
