# Generated by Django 3.2.6 on 2022-07-26 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker',
            old_name='emp_name',
            new_name='empname',
        ),
    ]
