# Generated by Django 3.2.6 on 2022-06-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='clientname',
            field=models.CharField(default='C', help_text='Required', max_length=255),
        ),
    ]
