# Generated by Django 3.2.6 on 2024-04-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vista',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('firt_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('office', models.CharField(max_length=20)),
                ('reason', models.TextField(max_length=200)),
                ('time_in', models.DateTimeField()),
            ],
        ),
    ]
