# Generated by Django 3.2.6 on 2024-04-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='requirement',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('description', models.TextField(max_length=255)),
            ],
        ),
    ]
