# Generated by Django 3.2.6 on 2023-03-27 17:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('email', models.CharField(max_length=100)),
                ('gender', models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True)),
                ('phone', models.CharField(default='90001', max_length=100)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('category', models.IntegerField(choices=[(1, 'Coda'), (2, 'Dyc'), (3, 'General User')], default=999)),
                ('is_admin', models.BooleanField(default=False, verbose_name='Is admin')),
                ('is_employee', models.BooleanField(default=False, verbose_name='Is employee')),
                ('is_client', models.BooleanField(default=False, verbose_name='Is Client')),
                ('is_applicant', models.BooleanField(default=False, verbose_name='Is applicant')),
                ('is_employee_contract_signed', models.BooleanField(default=False)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/doc/')),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        # migrations.AddField(
        #     model_name='customeruser',
        #     name='is_employee_contract_signed',
        #     field=models.BooleanField(default=False),
        # ),
        migrations.AlterField(
            model_name='customeruser',
            name='sub_category',
            field=models.IntegerField(blank=True, choices=[(0, 'No Selection'), (1, 'Job Support'), (2, 'Student'), (3, 'Full Time'), (4, 'Contractual'), (5, 'Agent'), (6, 'Dc48Kenya'), (7, 'Dyc'), (8, 'Other')], null=True),
        ),
        migrations.CreateModel(
            name='DYCUserCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(4, 'Dyc Business'), (5, 'Dyc Staff'), (6, 'Dyc Student'), (0, 'No Selection'), (8, 'Other')], default=999)),
                ('sub_category', models.IntegerField(blank=True, choices=[(1, 'No Selection'), (2, 'Agent'), (3, 'Other')], null=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True, verbose_name='entered on')),
                ('user', models.ForeignKey(blank=True, limit_choices_to={'is_active': True, 'is_employee': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DYCUser', to='accounts.customuser', verbose_name='DYCUser')),
            ],
            options={
                'ordering': ['-entry_date'],
            },
        ),
        migrations.CreateModel(
            name='CODAUserCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.IntegerField(choices=[(1, 'Job Applicant'), (2, 'Coda Staff Member'), (3, 'Client Or Customer Or Student'), (0, 'No Selection'), (8, 'Other')], default=999)),
                ('sub_category', models.IntegerField(blank=True, choices=[(0, 'No Selection'), (1, 'Job Support'), (2, 'Student'), (3, 'Full Time'), (4, 'Contractual'), (5, 'Agent'), (8, 'Other')], null=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True, verbose_name='entered on')),
                ('user', models.ForeignKey(blank=True, limit_choices_to=models.Q(('is_active', True)), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='accounts.customuser', verbose_name='User')),
            ],
            options={
                'ordering': ['-entry_date'],
            },
        ),
    ]
