# Generated by Django 3.2.6 on 2024-06-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField()),
                ('skills_expertise', models.TextField()),
                ('number_of_connects', models.IntegerField()),
                ('min_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_duration', models.IntegerField()),
                ('max_duration', models.IntegerField()),
                ('project_type', models.TextField()),
                ('deliverables', models.TextField()),
                ('links', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
