# Generated by Django 3.2.6 on 2023-09-29 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialcategory',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
