# Generated by Django 3.2.6 on 2024-04-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='shopping',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('cost_price', models.PositiveIntegerField()),
                ('pay_type', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
