# Generated by Django 3.2.6 on 2022-02-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220207_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='category',
            field=models.IntegerField(choices=[(1, 'Client Or Customer Or Student'), (2, 'Applicant Job Applicant')]),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True),
        ),
    ]
