# Generated by Django 3.2.6 on 2022-07-06 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220630_0350'),
        ('accounts', '0002_auto_20220630_1749'),
    ]

    operations = [
    ]
