# Generated by Django 3.2.6 on 2022-03-03 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220303_0212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker',
            old_name='Plan',
            new_name='plan',
        ),
    ]
