# Generated by Django 4.0.3 on 2022-03-28 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customeruser_is_admin_customeruser_is_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='is_employee',
        ),
    ]
