# Generated by Django 3.2.6 on 2023-12-26 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_credentialcategory_is_active'),
        ('accounts', '0002_auto_20231224_1356'),
    ]

    operations = [
    ]
