# Generated by Django 3.0.7 on 2021-05-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210523_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='category',
            field=models.IntegerField(choices=[(1, 'Dataanalysis'), (2, 'Trading'), (3, 'Employee'), (4, 'Applicant')], default=9999),
        ),
    ]
