# Generated by Django 3.2.6 on 2022-06-15 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tracker_clientname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='clientname',
        ),
        migrations.AddField(
            model_name='tracker',
            name='employee',
            field=models.CharField(default='C', help_text='Required', max_length=255, verbose_name='Employee'),
        ),
    ]
