# Generated by Django 3.2.6 on 2022-07-01 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customeruser_sub_category'),
        ('accounts', '0003_merge_0002_auto_20220630_0350_0002_auto_20220630_1749'),
    ]

    operations = [
    ]
