# Generated by Django 4.0.3 on 2022-03-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customeruser_is_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='is_applicant',
            field=models.BooleanField(default=True, verbose_name='Is employee'),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='is_employee',
            field=models.BooleanField(default=False, verbose_name='Is employee'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Is admin'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='is_customer',
            field=models.BooleanField(default=False, verbose_name='Is employee'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
