# Generated by Django 3.2.6 on 2022-07-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merge_0002_auto_20220630_0350_0002_auto_20220630_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='sub_category',
            field=models.CharField(choices=[('Requirements', 'Requirements'), ('Troubleshooting', 'Troubleshooting'), ('Development', 'Development'), ('Testing', 'Testing'), ('Other', 'Other')], default='Other', max_length=25),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='category',
            field=models.CharField(choices=[('Job_Support', 'Job_Support'), ('Interview', 'Interview'), ('Training', 'Training'), ('Mentorship', 'Mentorship'), ('Other', 'Other')], max_length=25),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='task',
            field=models.CharField(choices=[('reporting', 'reporting'), ('database', 'database'), ('Business Analysis', 'Business Analysis'), ('Data Cleaning', 'Data Cleaning'), ('Other', 'Other')], max_length=25),
        ),
    ]
