# Generated by Django 3.2.6 on 2022-07-07 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customeruser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeruser',
            options={'ordering': ['-date_joined']},
        ),
    ]
