# Generated by Django 3.2.6 on 2022-02-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220207_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='category',
            field=models.IntegerField(choices=[(1, 'Client Or Customer Or Student'), (2, 'Applicant Job Applicant')], default=9999),
        ),
    ]
