# Generated by Django 3.2.6 on 2022-06-15 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220615_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Client Name'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='employee',
            field=models.CharField(default='C', help_text='Required', max_length=255, verbose_name='Employee Name'),
        ),
    ]
