# Generated by Django 4.0.3 on 2022-03-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customeruser_is_applicant_customeruser_is_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='is_customer',
        ),
        migrations.AddField(
            model_name='customeruser',
            name='is_client',
            field=models.BooleanField(default=False, verbose_name='Is Client'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='is_applicant',
            field=models.BooleanField(default=True, verbose_name='Is applicant'),
        ),
    ]
