# Generated by Django 3.2.6 on 2022-06-15 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220615_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='author',
            field=models.ForeignKey(limit_choices_to={'is_client': True}, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='Client Name'),
        ),
    ]
