# Generated by Django 3.2.6 on 2022-02-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customeruser_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='category',
            field=models.IntegerField(choices=[(1, 'Client Or Customer Or Student'), (2, 'Applicant Or Job Applicant')]),
        ),
    ]
