# Generated by Django 3.2.6 on 2022-07-12 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_credential_credentialcategory_department'),
        ('accounts', '0005_merge_20220712_1626'),
    ]

    operations = [
    ]
