# Generated by Django 3.2.6 on 2022-06-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_tracker_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='employee',
            field=models.CharField(default='CODA', help_text='Required', max_length=255, verbose_name='Employee Name'),
        ),
    ]
