# Generated by Django 4.0.3 on 2022-03-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customeruser_is_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='category',
            field=models.IntegerField(choices=[(1, 'Applicant Or Job Applicant'), (2, 'Coda Staff Member'), (3, 'Client Or Customer Or Student')], default=999),
        ),
    ]
