# Generated by Django 3.2.6 on 2022-07-17 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_20220712_2349'),
        ('accounts', '0006_merge_20220712_1708'),
    ]

    operations = [
    ]
