# Generated by Django 3.2.6 on 2022-06-19 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_tracker_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='resume',
        ),
    ]
