# Generated by Django 3.2.6 on 2022-05-31 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customeruser_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='sub_category',
            field=models.IntegerField(choices=[(1, 'Client Or Customer'), (2, 'Student')], default=999),
        ),
    ]
