# Generated by Django 3.2.6 on 2022-06-19 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_customeruser_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/doc/'),
        ),
    ]
