# Generated by Django 3.2.6 on 2022-06-06 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customeruser_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='sub_category',
        ),
    ]
