# Generated by Django 3.2.6 on 2022-07-17 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_merge_20220712_2133'),
        ('accounts', '0008_auto_20220717_0341'),
    ]

    operations = [
    ]
