# Generated by Django 3.2.6 on 2022-06-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customeruser_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='sub_category',
            field=models.IntegerField(blank=True, choices=[(1, 'Client Or Customer'), (2, 'Student')], default=999, null=True),
        ),
    ]
