# Generated by Django 3.2.6 on 2022-07-21 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_20220717_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='employee',
            field=models.ForeignKey(default=1, help_text='Required', limit_choices_to={'is_active': True, 'is_employee': True}, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Employee Name'),
        ),
    ]
