# Generated by Django 3.2.6 on 2022-06-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customeruser_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes'),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='sub_category',
            field=models.IntegerField(blank=True, choices=[(0, 'No Selection'), (1, 'Client Or Customer'), (2, 'Student'), (3, 'Full Time'), (4, 'Contractual'), (5, 'Part Time')], null=True),
        ),
    ]
