# Generated by Django 3.2.6 on 2022-07-22 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_tracker_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credential',
            old_name='user_type',
            new_name='user_types',
        ),
    ]
