# Generated by Django 3.2.6 on 2022-07-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_user_type_credential_user_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='employee',
            field=models.CharField(default='CODA', help_text='Required', max_length=255, verbose_name='Employee Name'),
        ),
    ]
