# Generated by Django 3.2.6 on 2022-06-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20220611_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/doc/'),
        ),
    ]
