# Generated by Django 3.2.6 on 2022-07-26 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_tracker_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='emp_name',
            field=models.ForeignKey(default=1, limit_choices_to={'is_active': True, 'is_employee': True}, on_delete=django.db.models.deletion.RESTRICT, related_name='employee_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='employee',
            field=models.CharField(default='CODA', help_text='Required', max_length=255, verbose_name='Company/End Client'),
        ),
    ]
