# Generated by Django 3.2.6 on 2022-07-25 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_tracker_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='employee',
            field=models.ForeignKey(default=999, help_text='Required', limit_choices_to=models.Q(('is_active', True)), on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Employee Name'),
        ),
    ]
