# Generated by Django 3.2.6 on 2022-06-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant_profile',
            name='section',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
