# Generated by Django 3.2.6 on 2024-04-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAsset_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('category', models.CharField(blank=True, max_length=225, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('purchase_date', models.DateTimeField()),
                ('description', models.TextField()),
            ],
        ),
    ]
