# Generated by Django 3.0.7 on 2020-11-17 07:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('topic', models.CharField(default=None, max_length=100)),
                ('employee_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('punctuality', models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')])),
                ('communication', models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')])),
                ('understanding', models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')])),
                ('rated_by', models.CharField(default='CEO', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rated',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('topic', models.CharField(default=None, max_length=100)),
                ('rating_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('punctuality', models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')])),
                ('communication', models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')])),
                ('understanding', models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')])),
            ],
        ),
        migrations.AlterField(
            model_name='inteviewuploads',
            name='SQL',
            field=models.FileField(upload_to='interviewdb/doc/'),
        ),
        migrations.AlterField(
            model_name='inteviewuploads',
            name='alteryx',
            field=models.FileField(upload_to='interviewalteryx/doc/'),
        ),
        migrations.AlterField(
            model_name='inteviewuploads',
            name='interviewppt',
            field=models.FileField(upload_to='interviewppt/doc/'),
        ),
        migrations.AlterField(
            model_name='inteviewuploads',
            name='other',
            field=models.FileField(upload_to='interviewother/doc/'),
        ),
        migrations.AlterField(
            model_name='inteviewuploads',
            name='tableau',
            field=models.FileField(upload_to='interviewtab/doc/'),
        ),
    ]
