# Generated by Django 3.2.6 on 2024-04-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='receiver_asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('activity_date', models.DateTimeField()),
                ('receipt_link', models.CharField(max_length=100, null=True)),
                ('qty', models.DecimalField(decimal_places=0, max_digits=10, null=True)),
            ],
        ),
    ]
