# Generated by Django 3.2.6 on 2022-07-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_profile',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Is featured'),
        ),
    ]
