# Generated by Django 3.2.6 on 2022-01-24 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='gender',
        ),
    ]
