# Generated by Django 3.2.6 on 2022-07-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant_profile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is featured'),
        ),
    ]
