# Generated by Django 3.0.7 on 2020-11-16 05:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rated',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('topic', models.CharField(default=None, max_length=100)),
                ('rating_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('punctuality', models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')])),
                ('communication', models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')])),
                ('understanding', models.IntegerField(choices=[(1, 'Very Poor'), (2, 'Poor'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')])),
            ],
        ),
        migrations.CreateModel(
            name='Uploads',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, null=True)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('interviewppt', models.FileField(upload_to='interviewppt/ppt/')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], default=None),
        ),
        migrations.AlterField(
            model_name='inteviewuploads',
            name='SQL',
            field=models.FileField(upload_to='interviewdb/dba/'),
        ),
        migrations.AlterField(
            model_name='inteviewuploads',
            name='other',
            field=models.FileField(upload_to='interviewother/general/'),
        ),
        migrations.AlterField(
            model_name='inteviewuploads',
            name='tableau',
            field=models.FileField(upload_to='interviewtab/tab/'),
        ),
    ]
