# Generated by Django 3.2.6 on 2024-04-10 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='exception_client',
            fields=[
                ('exception_id', models.AutoField(primary_key=True, serialize=False)),
                ('exception_date', models.DateField()),
                ('exception_week', models.IntegerField()),
                ('exception_year', models.IntegerField()),
                ('comments', models.TextField(max_length=255)),
                ('exception_type_id', models.IntegerField()),
                ('project_user_id', models.IntegerField()),
                ('vacations', models.IntegerField()),
            ],
        ),
    ]
