# Generated by Django 3.2.6 on 2023-02-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='emergency_address',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_citizenship',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_email',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_national_id_no',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id_file',
            field=models.ImageField(default='xyz.jpg', upload_to='id_files/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='national_id_no',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
