# Generated by Django 3.2.6 on 2023-12-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='google_image_id',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
