# Generated by Django 3.2.6 on 2024-02-26 15:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceSheet_Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Balance Sheets',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Balancesheet_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('balance_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='application.balancesheet_summary')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.balancesheet_category')),
            ],
            options={
                'verbose_name_plural': 'Balance Sheet Entries',
            },
        ),
    ]
