# Generated by Django 3.2.6 on 2024-04-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentStrategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=50)),
                ('expiry', models.DateField()),
                ('strike_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mid_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ask_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('implied_volatility_rank', models.DecimalField(decimal_places=2, max_digits=5)),
                ('earnings_date', models.DateField(blank=True, null=True)),
                ('earning_flag', models.BooleanField(default=False)),
                ('stock_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('raw_return', models.DecimalField(decimal_places=2, max_digits=10)),
                ('annualized_return', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comment', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Investment Strategies',
            },
        ),
    ]
