# Generated by Django 3.2.6 on 2022-07-11 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application_profile',
            name='is_active',
        ),
    ]
