# Generated by Django 3.2.6 on 2022-07-08 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_applicant_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant_profile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='applicant_profile',
            name='section',
        ),
        migrations.RemoveField(
            model_name='applicant_profile',
            name='upload_a',
        ),
        migrations.RemoveField(
            model_name='applicant_profile',
            name='upload_b',
        ),
        migrations.RemoveField(
            model_name='applicant_profile',
            name='upload_c',
        ),
        migrations.RemoveField(
            model_name='applicant_profile',
            name='user',
        ),
    ]
