# Generated by Django 3.2.6 on 2024-04-13 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_investmentcontent_investmentstrategy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvestmentContent',
            new_name='XInvestmentContent',
        ),
        migrations.RenameModel(
            old_name='InvestmentStrategy',
            new_name='XInvestmentStrategy',
        ),
        migrations.AlterModelOptions(
            name='xinvestmentstrategy',
            options={'verbose_name_plural': 'XInvestment Strategies'},
        ),
    ]
