# Generated by Django 3.0.7 on 2020-09-16 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cover',
            field=models.FileField(default=None, upload_to='cover/doc/'),
        ),
        migrations.AddField(
            model_name='application',
            name='phone',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
