# Generated by Django 3.2.6 on 2021-10-18 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_remove_firstupload_applicant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FirstUpload',
        ),
    ]
