# Generated by Django 3.2.6 on 2024-04-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_investmentstrat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investmentstrat',
            name='id',
        ),
        migrations.AlterField(
            model_name='investmentstrat',
            name='symbol',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
