# Generated by Django 3.2.6 on 2022-07-12 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_application_profile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applicant_Profile',
        ),
    ]
