# Generated by Django 3.2.6 on 2022-07-01 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_applicant_profile_section'),
        ('application', '0002_alter_application_resume'),
    ]

    operations = [
    ]
