# Generated by Django 3.0.7 on 2020-11-18 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20201118_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstupload',
            name='upload_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
