# Generated by Django 3.2.6 on 2022-08-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20220716_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='rated',
            name='deployment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rated',
            name='development',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rated',
            name='projectDescription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rated',
            name='requirementsAnalysis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rated',
            name='testing',
            field=models.BooleanField(default=False),
        ),
    ]
