# Generated by Django 3.2.6 on 2022-06-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_applicant_profile_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant_profile',
            name='section',
            field=models.CharField(default='', max_length=2),
        ),
    ]
