# Generated by Django 3.2.6 on 2024-04-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20240415_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentstrat',
            name='symbol',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
