# Generated by Django 3.0.7 on 2020-11-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_firstupload_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstupload',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='firstupload',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
