# Generated by Django 3.0.7 on 2020-09-16 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20200916_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='country',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='last_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
