# Generated by Django 3.0.7 on 2020-11-03 06:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20201027_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteviewUploads',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, null=True)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('interviewppt', models.FileField(upload_to='interviewppt/ppt/')),
                ('tableau', models.FileField(default=None, upload_to='interviewtab/tab/')),
                ('alteryx', models.FileField(upload_to='interviewalteryx/alteryx/')),
                ('SQL', models.FileField(default=None, upload_to='interviewdb/dba/')),
                ('other', models.FileField(default=None, upload_to='interviewother/general/')),
                ('Applicant', models.ManyToManyField(to='application.Application')),
            ],
        ),
    ]
