# Generated by Django 3.2.6 on 2022-07-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_merge_20220701_0907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant_profile',
            old_name='applicant',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='applicant_profile',
            name='section',
            field=models.CharField(default='', max_length=2),
        ),
    ]
