# Generated by Django 3.2.6 on 2022-08-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20220808_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rated',
            name='understanding',
        ),
        migrations.AddField(
            model_name='rated',
            name='totalpoints',
            field=models.IntegerField(default=0),
        ),
    ]
