# Generated by Django 3.0.7 on 2021-06-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20210609_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='policy_type',
            field=models.CharField(choices=[('Leave', 'Leave'), ('Working Hours', 'Working Hours'), ('Working Days', 'Working Days'), ('Unpaid Training', 'Unpaid_Training'), ('Location', 'Location'), ('Other', 'Other')], default='Other', max_length=25),
        ),
    ]
