# Generated by Django 3.2.6 on 2022-01-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_remove_application_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], default=9999),
        ),
    ]
