# Generated by Django 3.0.7 on 2020-10-28 00:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20201027_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='inteviewupload',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
