# Generated by Django 3.0.7 on 2020-09-16 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20200916_1841'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='application',
            new_name='Applicant',
        ),
    ]
