# Generated by Django 3.0.7 on 2020-10-28 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_inteviewupload_upload_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inteviewupload',
            name='upload_date',
        ),
    ]
