# Generated by Django 3.0.7 on 2020-09-16 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20200916_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(default=None, max_length=100)),
                ('phone', models.CharField(default=None, max_length=100)),
                ('country', models.CharField(default=None, max_length=100)),
                ('resume', models.FileField(upload_to='resumes/doc/')),
                ('cover', models.FileField(default=None, upload_to='cover/doc/')),
            ],
        ),
    ]
