# Generated by Django 3.2.6 on 2022-08-09 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20220808_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rated',
            name='communication',
        ),
        migrations.RemoveField(
            model_name='rated',
            name='punctuality',
        ),
    ]
