# Generated by Django 3.0.7 on 2021-08-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_reporting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporting',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=25, null=True),
        ),
    ]
