# Generated by Django 3.0.7 on 2020-10-30 04:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_remove_inteviewupload_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='inteviewupload',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
