# Generated by Django 3.0.7 on 2020-09-16 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='cover',
        ),
    ]
