# Generated by Django 3.0.7 on 2021-08-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20210811_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporting',
            name='method',
            field=models.CharField(blank=True, choices=[('Direct', 'Direct'), ('Indirect', 'Indirect')], max_length=25, null=True),
        ),
    ]
