# Generated by Django 3.2.6 on 2022-08-16 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0007_alter_rated_employeename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rated',
            name='employeename',
            field=models.ForeignKey(default=1, limit_choices_to=models.Q(('is_employee', True)), on_delete=django.db.models.deletion.CASCADE, related_name='rating_empname', to=settings.AUTH_USER_MODEL),
        ),
    ]
