# Generated by Django 3.0.7 on 2020-09-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_remove_applicant_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='cover',
            field=models.FileField(default='None', upload_to='cover/doc/'),
        ),
    ]
