# Generated by Django 3.0.7 on 2021-08-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20210811_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporting',
            name='interview_type',
            field=models.CharField(choices=[('Internal Interview', 'Internal Interview'), ('First Interview', 'First Interview'), ('Second Interview', 'Second Interview'), ('Third Interview', 'Third Interview')], max_length=25),
        ),
    ]
