# Generated by Django 3.2.6 on 2022-08-16 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0009_auto_20220816_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rated',
            name='employeename',
            field=models.ForeignKey(blank=True, default=1, limit_choices_to=models.Q(('is_employee', True), ('is_applicant', True), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='rating_empname', to=settings.AUTH_USER_MODEL),
        ),
    ]
