# Generated by Django 3.2.6 on 2022-08-17 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_alter_rated_employeename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rated',
            name='topic',
            field=models.CharField(choices=[('Tableau-Landing Page', 'Tableau-Landing Page'), ('Tableau-Executive Page', 'Tableau-Executive Page'), ('Tableau-Other', 'Tableau-Other'), ('Alteryx', 'Alteryx'), ('Database', 'Database'), ('Other', 'Other')], default='Other', max_length=255),
        ),
    ]
