# Generated by Django 3.0.7 on 2020-09-17 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_remove_application_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='country',
        ),
        migrations.RemoveField(
            model_name='application',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='application',
            name='phone',
        ),
    ]
