# Generated by Django 3.0.7 on 2020-09-17 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20200916_2011'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applicant',
        ),
    ]
