# Generated by Django 3.0.7 on 2020-09-17 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_delete_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='cover',
            field=models.FileField(default=None, upload_to='cover/doc/'),
        ),
    ]
