# Generated by Django 3.0.7 on 2020-09-17 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_application_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='cover',
        ),
        migrations.AddField(
            model_name='application',
            name='last_name',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
