# Generated by Django 3.0.7 on 2020-09-17 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_auto_20200916_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='last_name',
        ),
    ]
