# Generated by Django 3.2.6 on 2023-02-18 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, default='background', max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_name', models.CharField(default=None, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backgroundImage', models.ImageField(default='default.jpg', upload_to='background')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, default='Data Analysis', max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Financial', 'Financial'), ('Health', 'Health'), ('Family', 'Family'), ('Other', 'Other')], default='Other', max_length=25)),
                ('goal', models.CharField(choices=[('Business', 'Business'), ('Employment', 'Employment'), ('Savings', 'Savings'), ('Insurance', 'Insurance'), ('Trips', 'Trips')], default='Other', max_length=25)),
                ('status', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Low', max_length=25)),
                ('task', models.CharField(default='CODA', max_length=255)),
                ('duration', models.IntegerField(default=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('what', models.TextField()),
                ('why', models.TextField()),
                ('how', models.TextField()),
                ('comments', models.TextField(blank=True, default='No Comment', null=True)),
                ('doc', models.FileField(blank=True, null=True, upload_to='Uploads/Support_Docs/')),
                ('pptlink', models.CharField(blank=True, default='link', max_length=300, null=True)),
                ('videolink', models.CharField(blank=True, default='Video', max_length=300, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_answered', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=True)),
                ('planner', models.ForeignKey(blank=True, default=1, limit_choices_to=models.Q(('is_admin', True), ('is_superuser', True), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planner', to=settings.AUTH_USER_MODEL)),
                ('responsible_party', models.ForeignKey(default=1, limit_choices_to=models.Q(('is_employee', True), ('is_admin', True), ('is_superuser', True), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Plan',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.service')),
            ],
        ),
    ]
