# Generated by Django 3.2.6 on 2024-06-13 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, default='background', max_length=200, null=True)),
                ('image_string', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='background', null=True)),
                ('service_image', models.ImageField(blank=True, default='background', null=True, upload_to='images/')),
                ('image_url', models.CharField(blank=True, default='background', max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Assets',
            },
        ),
        migrations.CreateModel(
            name='Readme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(default='slug', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('installation', models.TextField(blank=True, null=True)),
                ('usage', models.TextField(blank=True, null=True)),
                ('configuration', models.TextField(blank=True, null=True)),
                ('deployment', models.TextField(blank=True, null=True)),
                ('contributing', models.TextField(blank=True, null=True)),
                ('license', models.TextField(blank=True, null=True)),
                ('credits', models.TextField(blank=True, null=True)),
                ('contact', models.TextField(blank=True, null=True)),
                ('additional_sections', models.TextField(blank=True, null=True)),
                ('links', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Readme',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.PositiveIntegerField(blank=True, null=True)),
                ('title', models.CharField(default='training', max_length=254)),
                ('slug', models.SlugField(default='slug', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('sub_titles', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
    ]
