# Generated by Django 3.2.6 on 2022-06-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_name', models.CharField(default=None, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
            ],
        ),
    ]
