# Generated by Django 3.2.6 on 2023-09-04 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='ClientAvailability',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('day', models.CharField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], max_length=100)),
        #         ('start_time', models.TimeField()),
        #         ('end_time', models.TimeField()),
        #         ('time_standards', models.CharField(choices=[('PST', 'PST'), ('CST', 'CST'), ('EST', 'EST'), ('EAT', 'EAT')], max_length=100)),
        #         ('topic', models.CharField(blank=True, max_length=254, null=True)),
        #         ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Clint', to=settings.AUTH_USER_MODEL)),
        #     ],
        # ),
        # migrations.CreateModel(
        #     name='Pricing',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('serial', models.PositiveIntegerField(blank=True, null=True)),
        #         ('title', models.CharField(max_length=254)),
        #         ('description', models.TextField(blank=True, null=True)),
        #         ('price', models.FloatField()),
        #         ('duration', models.PositiveIntegerField(blank=True, null=True)),
        #         ('contract_length', models.IntegerField(choices=[(1, 'One Month'), (2, 'Two Months'), (3, 'Three Months'), (12, 'Open')], default=3)),
        #         ('is_active', models.BooleanField(default=True)),
        #     ],
        #     options={
        #         'verbose_name_plural': 'Pricing',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='ServiceCategory',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(max_length=254)),
        #         ('slug', models.SlugField(blank=True, null=True, unique=True)),
        #         ('description', models.TextField(blank=True, null=True)),
        #         ('service', models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='main.service')),
        #     ],
        #     options={
        #         'verbose_name_plural': 'Service Categories',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='Testimonials',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('title', models.CharField(max_length=100)),
        #         ('slug', models.SlugField(max_length=255, unique=True)),
        #         ('content', models.TextField()),
        #         ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
        #         ('writer', models.ForeignKey(limit_choices_to=models.Q(('is_staff', True), ('is_client', True), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='writer name')),
        #     ],
        #     options={
        #         'verbose_name_plural': 'Testimonials',
        #     },
        # ),
        migrations.AlterField(
            model_name='plan',
            name='category',
            field=models.CharField(choices=[('Financial', 'Financial'), ('Health', 'Health'), ('Family', 'Family'), ('Work', 'Work'), ('Other', 'Other')], default='Other', max_length=25),
        ),
        migrations.AlterField(
            model_name='plan',
            name='goal',
            field=models.CharField(choices=[('Business', 'Business'), ('Employment', 'Employment'), ('Savings', 'Savings'), ('Insurance', 'Insurance'), ('Relationship', 'Relationship'), ('Trips', 'Trips'), ('Other', 'Other')], default='Other', max_length=25),
        ),
        migrations.AlterField(
            model_name='plan',
            name='responsible_party',
            field=models.ForeignKey(default=1, limit_choices_to=models.Q(('is_staff', True), ('is_admin', True), ('is_superuser', True), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        # migrations.DeleteModel(
        #     name='Course',
        # ),
        # migrations.DeleteModel(
        #     name='CourseCategory',
        # ),
        # migrations.AddField(
        #     model_name='pricing',
        #     name='category',
        #     field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.servicecategory'),
        # ),
    ]
