# Generated by Django 3.2.6 on 2023-09-29 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('accounts', 'Registration'), ('Application', 'application'), ('Finance', 'Financial Information'), ('management', 'Employees Activities'), ('data', 'Data Analysis'), ('getdata', 'Automation'), ('investing', 'Investments'), ('main', 'General Information'), ('projectmanagement', 'Field Projects')], default='Other', max_length=25)),
                ('topic', models.CharField(default='Task', max_length=255)),
                ('question', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded', models.BooleanField(default=False)),
                ('searched_by', models.ForeignKey(limit_choices_to=models.Q(('is_staff', True), ('is_client', True), ('is_admin', True), ('is_superuser', True), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Search',
            },
        ),
    ]
