# Generated by Django 3.2.6 on 2023-03-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='subcategory',
            field=models.CharField(blank=True, default='Data Analysis', max_length=200, null=True),
        ),
    ]
