# Generated by Django 3.2.6 on 2024-01-26 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20240126_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='sub_titles',
            field=models.TextField(blank=True, null=True),
        ),



    ]
