# Generated by Django 3.2.6 on 2023-10-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='day',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='Sunday', max_length=25),
        ),
        migrations.AlterField(
            model_name='search',
            name='category',
            field=models.CharField(choices=[('accounts', 'Registration'), ('application', 'Application'), ('finance', 'Financial Information'), ('management', 'Employees Activities'), ('data', 'Data Analysis'), ('getdata', 'Automation'), ('investing', 'Investments'), ('main', 'General Information'), ('projectmanagement', 'Field Projects')], default='Other', max_length=25),
        ),
    ]
