# Generated by Django 3.2.6 on 2021-09-24 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expenses',
            name='receipt',
            field=models.FileField(upload_to='Uploads/Receipt_doc/'),
        ),
    ]
