# Generated by Django 3.0.7 on 2020-10-26 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_codadocuments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codadoc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=100)),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('codadoc', models.FileField(default=None, upload_to='codadoc/doc/')),
                ('description', models.TextField(blank=True, default=None, max_length=220)),
            ],
        ),
    ]
