# Generated by Django 3.2.6 on 2024-01-16 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20231027_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='assets',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assets',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assets',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pricing',
            name='discounted_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricing',
            name='is_direct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pricing',
            name='redirect_url_path',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PricingSubPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=254)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('my_pricing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pricing')),
            ],
            options={
                'verbose_name_plural': 'PricingSubPlan',
            },
        ),
    ]
