# Generated by Django 3.0.7 on 2021-02-25 16:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transanction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('project_name', models.CharField(default=None, max_length=100)),
                ('activity', models.CharField(default=None, max_length=100)),
                ('activity_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_method', models.IntegerField(choices=[(1, 'Cash'), (2, 'Mpesa'), (3, 'Check')])),
                ('amount', models.CharField(default=None, max_length=100)),
                ('description', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
