# Generated by Django 3.2.6 on 2022-03-02 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
