# Generated by Django 3.2.6 on 2022-01-25 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='created_by',
        ),
    ]
