# Generated by Django 3.2.6 on 2021-09-18 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='Receipt',
            new_name='receipt',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='activity',
        ),
    ]
