# Generated by Django 3.2.6 on 2021-09-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0002_auto_20210918_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
