# Generated by Django 3.0.7 on 2021-02-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0002_transanct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transanction',
        ),
        migrations.AddField(
            model_name='transanct',
            name='location',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
