# Generated by Django 3.0.7 on 2021-02-28 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0003_auto_20210228_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transanct',
            name='project_name',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
