# Generated by Django 3.0.7 on 2021-02-28 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectmanagement', '0006_auto_20210228_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transanct',
            name='location',
        ),
    ]
