# Generated by Django 3.2.6 on 2023-04-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashappMail',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('from_mail', models.CharField(max_length=255)),
                ('to_mail', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=50)),
                ('full_path', models.CharField(max_length=255)),
                ('text_mail', models.TextField()),
                ('received_date', models.CharField(max_length=255)),
                ('parsed_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.CharField(blank=True, max_length=255, null=True)),
                ('destination', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cashapp',
            },
        ),
        migrations.CreateModel(
            name='ReplyMail',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('from_mail', models.CharField(max_length=255)),
                ('to_mail', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('text_mail', models.TextField()),
                ('received_date', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'ReplyMail',
            },
        ),
    ]
