# Generated by Django 3.2.6 on 2023-08-29 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashappMail',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('from_mail', models.CharField(max_length=255)),
                ('to_mail', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=50)),
                ('full_path', models.CharField(max_length=255)),
                ('text_mail', models.TextField()),
                ('received_date', models.CharField(max_length=255)),
                ('parsed_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.CharField(blank=True, max_length=255, null=True)),
                ('destination', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cashapp',
            },
        ),
        migrations.CreateModel(
            name='Editable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('putsrow', models.PositiveIntegerField(blank=True, null=True)),
                ('callsrow', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'General',
            },
        ),
        migrations.CreateModel(
            name='ReplyMail',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('from_mail', models.CharField(max_length=255)),
                ('to_mail', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('text_mail', models.TextField()),
                ('received_date', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'ReplyMail',
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_in_code', models.CharField(blank=True, max_length=255, null=True)),
                ('reason_code_crash', models.CharField(blank=True, max_length=255, null=True)),
                ('exception', models.CharField(blank=True, max_length=255, null=True)),
                ('api', models.URLField(blank=True, max_length=255, null=True)),
                ('crated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_in_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Logs',
            },
        ),
    ]
