# Generated by Django 3.2.6 on 2023-05-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StanbicMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_reference', models.CharField(max_length=255)),
                ('transaction_type', models.CharField(max_length=255)),
                ('transaction_type_name', models.CharField(max_length=255)),
                ('transaction_origination_branch', models.CharField(max_length=255)),
                ('transaction_date', models.CharField(max_length=50)),
                ('narrative', models.CharField(max_length=255)),
                ('currency', models.TextField()),
                ('amount', models.CharField(max_length=255)),
                ('current_balance', models.CharField(blank=True, max_length=255, null=True)),
                ('parsed_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Stanbic',
            },
        ),
    ]
