# Generated by Django 3.2.6 on 2022-09-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0002_auto_20220907_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashappmail',
            name='subject',
            field=models.CharField(default='old ones without subject', max_length=100),
            preserve_default=False,
        ),
    ]
