# Generated by Django 3.2.6 on 2022-12-28 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0002_cryptomarket_stockmarket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cryptomarket',
        ),
    ]
