# Generated by Django 3.2.6 on 2022-11-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0002_replymail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Close',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('qty', models.PositiveIntegerField()),
                ('selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('executed_date', models.DateTimeField(blank=True, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
