# Generated by Django 3.2.6 on 2023-01-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0003_auto_20230117_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashappmail',
            name='amount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cashappmail',
            name='destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
