# Generated by Django 3.2.6 on 2022-09-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0003_cashappmail_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashappmail',
            name='from_mail',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cashappmail',
            name='subject',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cashappmail',
            name='to_mail',
            field=models.CharField(max_length=255),
        ),
    ]
