# Generated by Django 3.2.6 on 2023-01-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0004_auto_20230121_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashappmail',
            name='from_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cashappmail',
            name='to_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cashappmail',
            name='from_mail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
