# Generated by Django 3.2.6 on 2023-01-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0005_auto_20230121_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashappmail',
            name='from_mail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cashappmail',
            name='from_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cashappmail',
            name='to_mail',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cashappmail',
            name='to_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
