# Generated by Django 3.2.6 on 2023-01-21 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0006_auto_20230121_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashappmail',
            name='from_mail',
        ),
        migrations.RemoveField(
            model_name='cashappmail',
            name='to_mail',
        ),
    ]
