# Generated by Django 3.2.6 on 2023-01-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getdata', '0007_auto_20230121_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashappmail',
            name='from_name',
        ),
        migrations.RemoveField(
            model_name='cashappmail',
            name='to_name',
        ),
        migrations.AddField(
            model_name='cashappmail',
            name='from_mail',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cashappmail',
            name='to_mail',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
